### ISSUE TITLE
Implement Immigrant ships/camps

### ISSUE THREAD

**Issue by PowerSchill** [ldtteam/minecolonies-features#118]
# Prerequisites

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**
- [X] This is a feature request issue and not a bug report. Please create all bug reports [here](https://github.com/ldtteam/minecolonies/issues).

### Context

- Minecraft Version: 1.15.x+

### Expected behavior

>Immigrant ship/camp that comes with ~30 citizens that have stats as if their happiness level was 5.5. It would use the supply ship/camp schematics, and you would be able to choose if you wanted to accept them or not. If you didn't, they would ask for some food to continue on their journey trying to find a colony that will accept them. They would also have some low-level loot in their inventories, but you can only take it if you accept them into your colony. They would only come if you have at least 10 citizens, and the style of their ship/camp would be random.

#### Specifications

*

# Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Optionally add a comment with any insight and background you have that isn't already part of the conversation.

**Comment by ShadowProtocol** [comment]
If we have to explain every Wontfix, we'll be here a while. Also remember that Wonfix can also mean "this is so low on the priority list it will probably never get addressed in 5+ years, if ever".
In this case, we already have a more viable (i.e. slightly less bug prone) way of getting people in to the colony via visitors. 
This idea would add a higher chance factor to the game, making it less even for players who are competing. But even then, the players would probably only take one or two, maybe three colonists at a time (due to housing, and knowing what to do with them at that moment), which they can do from the tavern just as easily, in a much more controlled manner. 

That said, the idea is a clever one, and maybe some other idea will take inspiration from it.

**Comment by Thodor12** [comment]
As it currently stands mass immigration isn't viable anyway.
The colony doesn't grow too hard often anyway so there's never a need to suddenly gain 10+ citizens in 1 go.

On top of that there is the tavern which also provides you with randomized visitors from time to time.
