### ISSUE TITLE
Assigning guards to towers doesn't include trainees

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/minecolonies-features#192]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: MineColonies Official pack v3.0
- Structurize Version: MineColonies Official pack v3.0
- Related Mods and their Versions: none

## Expected behavior
If I had the option in the guard/barracks tower GUI to recruit from combat academy/archery turned on, I would expect to see the combat academy/archery trainees in the list of hireable people.

## Actual behavior
Trainees do not show up in the list of hireable people, only the unemployed do.

## Steps to reproduce the issue

1. Hire at least one person at an Archery and have at least one unemployed colonist
2. Turn on 'recruit from combat academy/archery' in an Archer guard tower and set its hiring mode to Manual
3. Check the hireable people at the guard tower

### Logs

- latest.log: I noticed this on the patreon 1.15 server, unless you need clientside logs I can't help
- crashlog: 

### Notes
See https://github.com/ldtteam/minecolonies/issues/5842#issuecomment-718276118

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by BellePullman** [comment]
In the same vein, it would be super helpful for Library Students to appear as possible workers when hiring non-military positions.  The Library and the military training academies are essentially "storing" workers while improving their stats, so it would make it a lot easier if they appeared as recruitable.  Logically using the same "Library Student: Joe L. Bloggs" format as they appear in housing lists, to make it clear what their current role is.
In fact, I think it would be most useful if all three sets of "Student" colonists appeared alongside the unemployed as recruitable for all job opportunities - sometimes it might be better to recruit a new miner, for example, from the military rather than the civilian students.  As long as their current status appeared by their names it would avoid any confusion.
Along that line, in the future it might be handy if the Library also included "Student Accommodation" in the same way the training academies now include accommodation?

**Comment by Justen-N** [comment]
Closed via ldtteam/minecolonies#6414
