### ISSUE TITLE
A way to show what's in stock and what's can be crafted on resource scroll

### ISSUE THREAD

**Issue by asoshinsky** [ldtteam/minecolonies-features#296]
### Prerequisites

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.603-ALPHA

## Is your feature request related to a problem?
At some point, it is a little bit difficult to remember all the items that are stored in the warehouse as well as all the recipes you have taught your settlers. So when a build request created, you look up items in the resource scroll. You see a list of items a builder needs and some have a label next to them saying they are going to be delivered from the warehouse. But it only shows when the builder requests it. Other items (I know they are in the warehouse) still red(missing) in the resource scroll.

## Feature description
A resource scroll could show:
- all the items that are in the warehouse, not just partially requested;
- items that can be crafted by the settlers (taught recipes)

### Notes or related things

This way it will be quite easy to understand which items you need to craft yourself and bring it to the builder/warehouse. You have probably noticed when a builder asks for a certain item, you craft and bring it to the warehouse, it is still red in the resource scroll.

---
## Viewers
* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by farmerjordan** [comment]
I was just about to make a feature request for this exact situation. I like to deliver the builder all the required resources for one build in bulk using the resource scroll. In this case, the warehouse items are not accounted for since they are not "actively requested" via the clipboard. Then I end up making duplicates of say stone brick stairs, when they were in the warehouse the entire time and could have been "counted" on the resource scroll. I think this is a highly necessary quality of life update.

**Comment by Thodor12** [comment]
This is now possible
