### ISSUE TITLE
New Worker: Assistant Governor

### ISSUE THREAD

**Issue by Justen-N** [ldtteam/minecolonies-features#309]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**( actually a possible solution to ~24:
#299, #296, #281, #278, #275, #274, #270, #240, #182, #164, #146, #143, #140, #115, #114, #79, #78, #77, #59, #53, #52, #32, #31, #24, #17

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?
Clearly, a large number of players are frustrated with some aspects of managing their colonies. Requests for a portable UI for any number of different management features are numerous, and there are many different suggestions. I'd like to compile most of these issues into one solution. 

## Feature description
A new worker called either the Butler, Personal Assistant, Assistant Governor or Aide-de-Camp. This worker would be tied to the town hall, allowing building the town hall to benefit the player more. This worker would be tiered like all other workers providing something similar to this list
* Tier 1: Hiring management
* Tier 2: Housing Management
* Tier 3: Warehouse Stock display
* Tier 4: Builder/Build queue management
* Tier 5: Citizen Controls: View available visitors, see who is/isn't sleeping, send colonists to sleep. 

### Notes or related things
This may be a tall order, especially considering the number of different lists that may need to be accessed in order to display the required information. I realize that this would also lower the 'difficulty' level in colony management, removing some of the travel aspects of managing your colony. That being said, I also feel that forcing players to travel to different huts to manage some colony wide attributes is an artificial difficulty addition in the first place, making it harder for some players to enjoy their experience with Minecolonies. 

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by hobnob11** [comment]
I was gonna open a feature request for a housing management ui but since this NPC sounds fantastic I'll tag onto this issue:

For the housing management, the UI would be a list of citizens, sorted by distance between their work and current housing.
Clicking on one brings up a second UI (or its one single UI with two lists, and selecting a citizen updates the second list) with a list of available beds, sorted by distance to the citizens workplace, with a single button to set the bed as the citizens new home.

The first list would also have a "evict" button, so that players could scroll to the bottom of the first list, where all of the citizens with very long distances to walk would be, and evict them to move them closer.

**Comment by Justen-N** [comment]
Spoke with the rest of the team, there are plans to address these issues in another format, so this will probably not be implemented.
