### ISSUE TITLE
dont you run away animals

### ISSUE THREAD

**Issue by Bossos11** [ldtteam/minecolonies-features#399]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.123-ALPHA-universal.jar

## Is your feature request related to a problem?
Yes, the animal farmer always leave the gates open and let the animal escape

## Feature description
Maybe add a block that the specific animals are attracted to like sheep are attracted to wheat and include it in the schematics

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
#392

**Comment by Bunzinator** [comment]
I would like to suggest a custom gate that is one way only to animals, but otherwise normal. It wouldn't effect that aesthetics of the schematics in any way, but would stop me returning to my colony after exploration to find 150 cows wandering the streets because the cowboy not competent enough to keep his cows wrangled.
