### ISSUE TITLE
Make miner obtain lucky raw drops as well as lucky ores

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#406]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Related Mods and their Versions:

## Is your feature request related to a problem?

Lucky ores include those that can have coal, lapis or even redstone, and those can be mined directly into drops with a normal pick.
Yet miners here can obtain them even without silk touch.

And the result is that no worker can mine those.
Smelting would be a waste of fuel, plus loots

## Enhancement or Change description

Miner produce raw drops for non smeltable ores
Miner produce additional drops with a Fortune pick
Miner will obtain ore blocks with a silk touch pick..

### Notes or related things

This mechanic will be applied in 1.17 anyway.

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
> This mechanic will be applied in 1.17 anyway.

Bit curious where you got this from 😄 
also, @Raycoms, iirc this is intentional?

**Comment by gattsuru** [comment]
1.17 is supposed to add the [raw ore](https://minecraft.fandom.com/wiki/Raw_Iron) mechanic, after which nearly _every_ ore block will have separate "silk touch" and normally mined results, with the largest ramifications for copper.  That won't necessarily change the Miner behavior, though, and there are some places where access to the ore blocks may be valuable.

((Assuming that Mojang/Microsoft doesn't change things.))

The `luckyOres` server-config does explicitly include `minecraft:redstone_ore`, `minecraft:coal_ore`, and `minecraft:lapis_ore`, and this is pretty easy to change for your own world.  It may be intentional as requiring either manual intervention or the smeltery, though.

**Comment by Raycoms** [comment]
In 1.17 our miner will silk-touch ALL ores minus coal
