### ISSUE TITLE
Make research time adjustable in the config

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies-features#548]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

Config option for research time.
Similar to sickness rarity or hunger modifier and children grow up time.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
this is already a thing in datapacks

**Comment by warning-djkajslh** [comment]
Nice.... I'd assume there is a detailed guide on how to do it on the wiki right?

**Comment by uecasm** [comment]
There is, although it's not as straightforward as just a number to tweak.  You would have to replace all the existing research with your own files that have different settings.  (Or at least make a new research branch that contains the ones you want to have a different time scale.)

If you really want to cheat research, just use creative mode.  Otherwise, it's intended that it takes a long time; you're supposed to be doing it in the background while working on something else.

**Comment by warning-djkajslh** [comment]
So I will have to config the time for each researches myself huh? Interesting.
The thing is I do not want it to instantly finished, I just want it to take lesser time, with the longest one being 1 hour.
