### ISSUE TITLE
Toggle blueprints on building stage so we can help builders with their work

### ISSUE THREAD

**Issue by Larkas** [ldtteam/minecolonies-features#600]
### Prerequisites

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.311-BETA
- Related Mods and their Versions: Structurize 0.13.254-ALPHA

## Is your feature request related to a problem?
It would be nice if you could better help the builder with their work.

## Enhancement or Change description
You can already help the builder with his work, but to do so you have to jump through hoops to see the building blueprint and see what goes where. A button on the hut's block toggling a visual blueprint (not unlike what we see when we are first placing the blueprint down) would help immensely with that!

### Notes or related things
Having something like Litematica's build overlay optionally on would allow us to actually help those guys, ESPECIALLY if there's an option, like Litematica's, to show each Y level at a time. A previous, [similar](https://github.com/ldtteam/minecolonies-features/issues/508), request was made to add a helmet for that - I disagree going with that option.

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
It's not recommended to help them build; there are certain blocks that will only work correctly if placed by a builder and not the player.  They are supposed to build slowly at first, but will get faster as they level up their skills and as you do research.  Minecolonies is not intended to be rushed.  (But if you really can't cope with their speed, there's a config setting for it too.)

**Comment by Jetheuel** [comment]
We understand about blocks that only work if placed by the builder (ie racks and beds and so forth) but the goal of seeing the blueprints in an easier format (whether by helmet as I suggested or the litematica format as suggested by Larkas) is also due to the desire to feel like you are working alongside the citizens rather than laze around and do nothing especially as the colony barely starts out.  Perhaps a potential solution to preventing builder required blocs being placed is having the in progress blueprints that are displayed not show the beds and racks, or have a red outline around the builder only blocks with words saying "Builder Required"?
