### ISSUE TITLE
Ware house book of the inventory list 

### ISSUE THREAD

**Issue by ToggleLite** [ldtteam/minecolonies-features#701]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context warehouse inventory feature 

- Minecraft Version:
- MineColonies Version:1.182-1.0.737-RELEASE.jar

## Is your feature request related to a problem?
I would like to have a way to know what is in your warehouse instead of having to go there and check

## Feature description
there should be a way to have a list of the items you have in your warehouse like it should give you a book of the items you have
### Notes or related things
no

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
What would benefit people from having this, we recently introduced a mechanic on the resource scroll where you can right click warehouses to get a snapshot of the warehouse contents to see if the warehouse has the materials that the builder is requesting.
You can pretty much see if the warehouse has the sufficient items.

Apart from this feature which already exists I really do not see a point for knowing everything you have, since you have to run over to your warehouse *anyway* to get the items you want.

**Comment by ToggleLite** [comment]
if i was to order something from like my post box i would like to know if the warehouse has enough of the item or if it doesn't have it.

**Comment by ToggleLite** [comment]
> if i was to order something from like my post box i would like to know if the warehouse has enough of the item or if it doesn't have it.

**Comment by YouKnowWhoRight** [comment]
> > if i was to order something from like my post box i would like to know if the warehouse has enough of the item or if it doesn't have it.

At that point, just try to order it. If its deliverying, then they have it, if not then they dont.
