### ISSUE TITLE
Fisher throwing in water success shall improve with Agility

### ISSUE THREAD

**Issue by leagris** [ldtteam/minecolonies-features#739]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.19.2
- MineColonies Version: 1.19.2-1.0.1152-BETA
- Related Mods and their Versions:

## Is your feature request related to a problem?
It is frustrating that Fisher continue to miss water as frequently, while throwing, and get the line stuck into solid blocks around; despite having significant Agility and Focus scores. 

## Enhancement or Change description
It would be fair, if the chance to throw into water and not miss, would improve proportionally to Fisher's Agility score.

### Notes or related things
Fisher (if not already), would map available water source blocks at reach of its working place; and then compute a Precision or Chance to target those blocks while throwing.
A fully agile Level 5 Fisher would never miss and throw into water 100% of the time.
While A Level 1 Agility 1 Fisher, would miss 50% of the time. 

![2022-12-27_16 17 08](https://user-images.githubusercontent.com/1111474/209692816-05752d0a-57c4-4705-bd5e-5c36eade18f4.png)
This Agility 25, Focus 30 Fisher, still throws into solid blocks 50% of the time

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
From a code standpoint, agility just improves the efficiency of the fisher. It does not actually improve the accuracy of throwing the line.
The bobber entity just gets a force applied to it and that's how it is thrown out, so depending on the placement of the hut you can run into problems where he will throw the line too far and just let it land in the ground.
Placement of the building here is the problem since it looks like he only has 3-4 blocks of throw length available.
