### ISSUE TITLE
Request for Miner AND Quarrier

### ISSUE THREAD

**Issue by GroeneKnuppel** [ldtteam/minecolonies-features#765]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [X ] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.19.2
- MineColonies Version: 1.0.1356-ALPHA

## Is your feature request related to a problem?
It's not rlly a problem, it's more a request.
It will help everyone not just myself

## Feature description
I saw that u cant have a miner and a quarrier at the same time. 
This is a nice thing to have and i dont see why this is disabled.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
This is by design.  Each mine can hire one or the other, so if you want both, make a second mine.

The 9x9 style pack includes a "quarrier" variant of the mine that's smaller and omits the mineshaft, especially for use in hiring a quarrier.  I don't think any other styles do this at present, but it might happen in the future.
