### ISSUE TITLE
Graveyard / Mausoleum building & worker for tracking

### ISSUE THREAD

**Issue by PowerSchill** [ldtteam/minecolonies-features#98]
Suggestion from Discord

### Expected behavior

> Can we get a mausoleum style graveyard building that keeps track of dead colonists in a sortable way? Like keep track of and filter by Job/Death Type/Family Name etc?
(https://discord.com/channels/139070364159311872/240841248750043137/718246552023334966)

# Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Optionally add a comment with any insight and background you have that isn't already part of the conversation.

**Comment by whorlbinder** [comment]
I was just about to suggest something like this as I've just been manually tracking deaths in my colony with an ever-expanding cemetery, lol

It'd be nice if this could be part of Civilian research; each improvement could lower mourning time.

**Comment by SioxGWolf** [comment]
Graveyard, which would be a crypt at the highest level, stores dead in as signs and such, (headstones would be nice if we can add those in, as well as stone signs) That keep track of the dead. with a limited number of slots for the dead. As long as a slot is available. The dead are inturned, the mourning spot is moved to the graveyard. And the time is reduced for mourning. When there are no more slots, all functions return to standard, until space is once again available. 

As the person above puts it, I would think it would be research instead of available off the bat....as well as improvable.

**Comment by ravenbuilder934** [comment]
https://github.com/ldtteam/minecolonies/issues/404 has some more suggestions

**Comment by darthvader45** [comment]
I wholeheartedly support this.  The worker title could be gravedigger.  Could function similarly to the cook in that lv 3 could add an assistant titled the undertaker, who would deal with the mourning and such, possibly providing a happiness boost to mourners (to represent the undertaker's job of comforting the mourners).

**Comment by Geoffrotism** [comment]
+1! I also would love a research (if it doesnt exist already) after unlocking the graveyard that shortens the mourning period?

**Comment by ravenbuilder934** [comment]
#311
